// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: xdg_shell
// Source: xdg-shell.xml

// Upstream protocol copyright and license:
// Copyright © 2008-2013 Kristian Høgsberg
// Copyright © 2013      Rafael Antognolli
// Copyright © 2013      Jasper St. Pierre
// Copyright © 2010-2013 Intel Corporation
// Copyright © 2015-2017 Samsung Electronics Co., Ltd
// Copyright © 2015-2017 Red Hat Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgshell

import (
	"sync"

	cross_wl_output "github.com/bnema/wlturbo/protocol/core"
	cross_wl_seat "github.com/bnema/wlturbo/protocol/core"
	cross_wl_surface "github.com/bnema/wlturbo/protocol/core"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_ROLE is the error role value.
const ERROR_ROLE = 0

// ERROR_DEFUNCT_SURFACES is the error defunct_surfaces value.
const ERROR_DEFUNCT_SURFACES = 1

// ERROR_NOT_THE_TOPMOST_POPUP is the error not_the_topmost_popup value.
const ERROR_NOT_THE_TOPMOST_POPUP = 2

// ERROR_INVALID_POPUP_PARENT is the error invalid_popup_parent value.
const ERROR_INVALID_POPUP_PARENT = 3

// ERROR_INVALID_SURFACE_STATE is the error invalid_surface_state value.
const ERROR_INVALID_SURFACE_STATE = 4

// ERROR_INVALID_POSITIONER is the error invalid_positioner value.
const ERROR_INVALID_POSITIONER = 5

// ERROR_UNRESPONSIVE is the error unresponsive value.
const ERROR_UNRESPONSIVE = 6

// ERROR_INVALID_INPUT is the error invalid_input value.
const ERROR_INVALID_INPUT = 0

// ANCHOR_NONE is the anchor none value.
const ANCHOR_NONE = 0

// ANCHOR_TOP is the anchor top value.
const ANCHOR_TOP = 1

// ANCHOR_BOTTOM is the anchor bottom value.
const ANCHOR_BOTTOM = 2

// ANCHOR_LEFT is the anchor left value.
const ANCHOR_LEFT = 3

// ANCHOR_RIGHT is the anchor right value.
const ANCHOR_RIGHT = 4

// ANCHOR_TOP_LEFT is the anchor top_left value.
const ANCHOR_TOP_LEFT = 5

// ANCHOR_BOTTOM_LEFT is the anchor bottom_left value.
const ANCHOR_BOTTOM_LEFT = 6

// ANCHOR_TOP_RIGHT is the anchor top_right value.
const ANCHOR_TOP_RIGHT = 7

// ANCHOR_BOTTOM_RIGHT is the anchor bottom_right value.
const ANCHOR_BOTTOM_RIGHT = 8

// GRAVITY_NONE is the gravity none value.
const GRAVITY_NONE = 0

// GRAVITY_TOP is the gravity top value.
const GRAVITY_TOP = 1

// GRAVITY_BOTTOM is the gravity bottom value.
const GRAVITY_BOTTOM = 2

// GRAVITY_LEFT is the gravity left value.
const GRAVITY_LEFT = 3

// GRAVITY_RIGHT is the gravity right value.
const GRAVITY_RIGHT = 4

// GRAVITY_TOP_LEFT is the gravity top_left value.
const GRAVITY_TOP_LEFT = 5

// GRAVITY_BOTTOM_LEFT is the gravity bottom_left value.
const GRAVITY_BOTTOM_LEFT = 6

// GRAVITY_TOP_RIGHT is the gravity top_right value.
const GRAVITY_TOP_RIGHT = 7

// GRAVITY_BOTTOM_RIGHT is the gravity bottom_right value.
const GRAVITY_BOTTOM_RIGHT = 8

// CONSTRAINT_ADJUSTMENT_NONE is the constraint_adjustment none value.
const CONSTRAINT_ADJUSTMENT_NONE = 0

// CONSTRAINT_ADJUSTMENT_SLIDE_X is the constraint_adjustment slide_x value.
const CONSTRAINT_ADJUSTMENT_SLIDE_X = 1

// CONSTRAINT_ADJUSTMENT_SLIDE_Y is the constraint_adjustment slide_y value.
const CONSTRAINT_ADJUSTMENT_SLIDE_Y = 2

// CONSTRAINT_ADJUSTMENT_FLIP_X is the constraint_adjustment flip_x value.
const CONSTRAINT_ADJUSTMENT_FLIP_X = 4

// CONSTRAINT_ADJUSTMENT_FLIP_Y is the constraint_adjustment flip_y value.
const CONSTRAINT_ADJUSTMENT_FLIP_Y = 8

// CONSTRAINT_ADJUSTMENT_RESIZE_X is the constraint_adjustment resize_x value.
const CONSTRAINT_ADJUSTMENT_RESIZE_X = 16

// CONSTRAINT_ADJUSTMENT_RESIZE_Y is the constraint_adjustment resize_y value.
const CONSTRAINT_ADJUSTMENT_RESIZE_Y = 32

// ERROR_NOT_CONSTRUCTED is the error not_constructed value.
const ERROR_NOT_CONSTRUCTED = 1

// ERROR_ALREADY_CONSTRUCTED is the error already_constructed value.
const ERROR_ALREADY_CONSTRUCTED = 2

// ERROR_UNCONFIGURED_BUFFER is the error unconfigured_buffer value.
const ERROR_UNCONFIGURED_BUFFER = 3

// ERROR_INVALID_SERIAL is the error invalid_serial value.
const ERROR_INVALID_SERIAL = 4

// XDG_SURFACE_ERROR_INVALID_SIZE is the error invalid_size value.
const XDG_SURFACE_ERROR_INVALID_SIZE = 5

// ERROR_DEFUNCT_ROLE_OBJECT is the error defunct_role_object value.
const ERROR_DEFUNCT_ROLE_OBJECT = 6

// ERROR_INVALID_RESIZE_EDGE is the error invalid_resize_edge value.
const ERROR_INVALID_RESIZE_EDGE = 0

// ERROR_INVALID_PARENT is the error invalid_parent value.
const ERROR_INVALID_PARENT = 1

// XDG_TOPLEVEL_ERROR_INVALID_SIZE is the error invalid_size value.
const XDG_TOPLEVEL_ERROR_INVALID_SIZE = 2

// RESIZE_EDGE_NONE is the resize_edge none value.
const RESIZE_EDGE_NONE = 0

// RESIZE_EDGE_TOP is the resize_edge top value.
const RESIZE_EDGE_TOP = 1

// RESIZE_EDGE_BOTTOM is the resize_edge bottom value.
const RESIZE_EDGE_BOTTOM = 2

// RESIZE_EDGE_LEFT is the resize_edge left value.
const RESIZE_EDGE_LEFT = 4

// RESIZE_EDGE_TOP_LEFT is the resize_edge top_left value.
const RESIZE_EDGE_TOP_LEFT = 5

// RESIZE_EDGE_BOTTOM_LEFT is the resize_edge bottom_left value.
const RESIZE_EDGE_BOTTOM_LEFT = 6

// RESIZE_EDGE_RIGHT is the resize_edge right value.
const RESIZE_EDGE_RIGHT = 8

// RESIZE_EDGE_TOP_RIGHT is the resize_edge top_right value.
const RESIZE_EDGE_TOP_RIGHT = 9

// RESIZE_EDGE_BOTTOM_RIGHT is the resize_edge bottom_right value.
const RESIZE_EDGE_BOTTOM_RIGHT = 10

// STATE_MAXIMIZED is the state maximized value.
const STATE_MAXIMIZED = 1

// STATE_FULLSCREEN is the state fullscreen value.
const STATE_FULLSCREEN = 2

// STATE_RESIZING is the state resizing value.
const STATE_RESIZING = 3

// STATE_ACTIVATED is the state activated value.
const STATE_ACTIVATED = 4

// STATE_TILED_LEFT is the state tiled_left value.
const STATE_TILED_LEFT = 5

// STATE_TILED_RIGHT is the state tiled_right value.
const STATE_TILED_RIGHT = 6

// STATE_TILED_TOP is the state tiled_top value.
const STATE_TILED_TOP = 7

// STATE_TILED_BOTTOM is the state tiled_bottom value.
const STATE_TILED_BOTTOM = 8

// STATE_SUSPENDED is the state suspended value.
const STATE_SUSPENDED = 9

// STATE_CONSTRAINED_LEFT is the state constrained_left value.
const STATE_CONSTRAINED_LEFT = 10

// STATE_CONSTRAINED_RIGHT is the state constrained_right value.
const STATE_CONSTRAINED_RIGHT = 11

// STATE_CONSTRAINED_TOP is the state constrained_top value.
const STATE_CONSTRAINED_TOP = 12

// STATE_CONSTRAINED_BOTTOM is the state constrained_bottom value.
const STATE_CONSTRAINED_BOTTOM = 13

// WM_CAPABILITIES_WINDOW_MENU is the wm_capabilities window_menu value.
const WM_CAPABILITIES_WINDOW_MENU = 1

// WM_CAPABILITIES_MAXIMIZE is the wm_capabilities maximize value.
const WM_CAPABILITIES_MAXIMIZE = 2

// WM_CAPABILITIES_FULLSCREEN is the wm_capabilities fullscreen value.
const WM_CAPABILITIES_FULLSCREEN = 3

// WM_CAPABILITIES_MINIMIZE is the wm_capabilities minimize value.
const WM_CAPABILITIES_MINIMIZE = 4

// ERROR_INVALID_GRAB is the error invalid_grab value.
const ERROR_INVALID_GRAB = 0

// XdgWmBaseInterface is the protocol interface name.
const XdgWmBaseInterface = "xdg_wm_base"

// XdgWmBase is the generated binding for xdg_wm_base version 7.
type XdgWmBase struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onPing     []func(serial uint32)
}

// NewXdgWmBase returns an unbound XdgWmBase.
func NewXdgWmBase(ctx *wl.Context) *XdgWmBase {
	obj := &XdgWmBase{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy this xdg_wm_base object. Destroying a bound xdg_wm_base object while there are surfaces still alive created by this xdg_wm_base object instance is illegal and will result in a defunct_surfaces error.
func (o *XdgWmBase) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_wm_base.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Create a positioner object. A positioner object is used to position surfaces relative to some parent surface. See the interface description and xdg_surface.get_popup for details.
func (o *XdgWmBase) CreatePositioner() (*XdgPositioner, error) {
	child := &XdgPositioner{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_wm_base.create_positioner", Child: child}, wl.ArgObject(child)); err != nil {
		return nil, err
	}
	return child, nil
}

// This creates an xdg_surface for the given surface. An xdg_surface is used as basis to define a role to a given surface, such as xdg_toplevel or xdg_popup. It also manages functionality shared between xdg_surface based surface roles. While xdg_surface itself is not a role, the corresponding surface may only be assigned a role extending xdg_surface, such as xdg_toplevel or xdg_popup. It is illegal to create an xdg_surface for a wl_surface which already has anassigned role and this will result in a role error. See the documentation of xdg_surface for more details about what an xdg_surface is and how it is used.
func (o *XdgWmBase) GetXdgSurface(surface *cross_wl_surface.Surface) (*XdgSurface, error) {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	child := &XdgSurface{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_wm_base.get_xdg_surface", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1)); err != nil {
		return nil, err
	}
	return child, nil
}

// A client must respond to a ping event with a pong request or the client may be deemed unresponsive. See xdg_wm_base.ping and xdg_wm_base.error.unresponsive.
func (o *XdgWmBase) Pong(serial uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "xdg_wm_base.pong"}, wl.ArgUint(serial)); err != nil {
		return err
	}
	return nil
}

// OnPing registers a handler for the ping event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgWmBase) OnPing(handler func(serial uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onPing = append(o.onPing, handler)
}

// handlersForPing returns the handlers registered for ping, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgWmBase) handlersForPing() []func(serial uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onPing
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgWmBase) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "uint,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_wm_base and calls the registered handlers.
func (o *XdgWmBase) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // ping
		serial := event.Uint32()

		for i, handler := range o.handlersForPing() {
			_ = i
			handler(serial)
		}
	default:
	}
}

// XdgPositionerInterface is the protocol interface name.
const XdgPositionerInterface = "xdg_positioner"

// XdgPositioner is the generated binding for xdg_positioner version 7.
type XdgPositioner struct {
	wl.BaseProxy
}

// NewXdgPositioner returns an unbound XdgPositioner.
func NewXdgPositioner(ctx *wl.Context) *XdgPositioner {
	obj := &XdgPositioner{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Notify the compositor that the xdg_positioner will no longer be used.
func (o *XdgPositioner) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_positioner.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Set the size of the surface that is to be positioned with the positioner object. The size is in surface-local coordinates and corresponds to the window geometry. See xdg_surface.set_window_geometry. If a zero or negative size is set the invalid_input error is raised.
func (o *XdgPositioner) SetSize(width int32, height int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_positioner.set_size"}, wl.ArgInt(width), wl.ArgInt(height)); err != nil {
		return err
	}
	return nil
}

// Specify the anchor rectangle within the parent surface that the child surface will be placed relative to. The rectangle is relative to the window geometry as defined by xdg_surface.set_window_geometry of the parent surface. When the xdg_positioner object is used to position a child surface, the anchor rectangle may not extend outside the window geometry of the positioned child's parent surface. If a negative size is set the invalid_input error is raised.
func (o *XdgPositioner) SetAnchorRect(x int32, y int32, width int32, height int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_positioner.set_anchor_rect"}, wl.ArgInt(x), wl.ArgInt(y), wl.ArgInt(width), wl.ArgInt(height)); err != nil {
		return err
	}
	return nil
}

// Defines the anchor point for the anchor rectangle. The specified anchor is used to derive an anchor point that the child surface will be positioned relative to. If a corner anchor is set (e.g. 'top_left' or 'bottom_right'), the anchor point will be at the specified corner; otherwise, the derived anchor point will be centered on the specified edge, or in the center of the anchor rectangle if no edge is specified.
func (o *XdgPositioner) SetAnchor(anchor uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "xdg_positioner.set_anchor"}, wl.ArgUint(anchor)); err != nil {
		return err
	}
	return nil
}

// Defines in what direction a surface should be positioned, relative to the anchor point of the parent surface. If a corner gravity is specified (e.g. 'bottom_right' or 'top_left'), then the child surface will be placed towards the specified gravity; otherwise, the child surface will be centered over the anchor point on any axis that had no gravity specified. If the gravity is not in the ‘gravity’ enum, an invalid_input error is raised.
func (o *XdgPositioner) SetGravity(gravity uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "xdg_positioner.set_gravity"}, wl.ArgUint(gravity)); err != nil {
		return err
	}
	return nil
}

// Specify how the window should be positioned if the originally intended position caused the surface to be constrained, meaning at least partially outside positioning boundaries set by the compositor. The adjustment is set by constructing a bitmask describing the adjustment to be made when the surface is constrained on that axis. If no bit for one axis is set, the compositor will assume that the child surface should not change its position on that axis when constrained. If more than one bit for one axis is set, the order of how adjustments are applied is specified in the corresponding adjustment descriptions. The default adjustment is none.
func (o *XdgPositioner) SetConstraintAdjustment(constraintAdjustment uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 5, Name: "xdg_positioner.set_constraint_adjustment"}, wl.ArgUint(constraintAdjustment)); err != nil {
		return err
	}
	return nil
}

// Specify the surface position offset relative to the position of the anchor on the anchor rectangle and the anchor on the surface. For example if the anchor of the anchor rectangle is at (x, y), the surface has the gravity bottom|right, and the offset is (ox, oy), the calculated surface position will be (x + ox, y + oy). The offset position of the surface is the one used for constraint testing. See set_constraint_adjustment. An example use case is placing a popup menu on top of a user interface element, while aligning the user interface element of the parent surface with some user interface element placed somewhere in the popup surface.
func (o *XdgPositioner) SetOffset(x int32, y int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 6, Name: "xdg_positioner.set_offset"}, wl.ArgInt(x), wl.ArgInt(y)); err != nil {
		return err
	}
	return nil
}

// When set reactive, the surface is reconstrained if the conditions used for constraining changed, e.g. the parent window moved. If the conditions changed and the popup was reconstrained, an xdg_popup.configure event is sent with updated geometry, followed by an xdg_surface.configure event.
func (o *XdgPositioner) SetReactive() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 7, Name: "xdg_positioner.set_reactive", Since: 3}); err != nil {
		return err
	}
	return nil
}

// Set the parent window geometry the compositor should use when positioning the popup. The compositor may use this information to determine the future state the popup should be constrained using. If this doesn't match the dimension of the parent the popup is eventually positioned against, the behavior is undefined. The arguments are given in the surface-local coordinate space.
func (o *XdgPositioner) SetParentSize(parentWidth int32, parentHeight int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 8, Name: "xdg_positioner.set_parent_size", Since: 3}, wl.ArgInt(parentWidth), wl.ArgInt(parentHeight)); err != nil {
		return err
	}
	return nil
}

// Set the serial of an xdg_surface.configure event this positioner will be used in response to. The compositor may use this information together with set_parent_size to determine what future state the popup should be constrained using.
func (o *XdgPositioner) SetParentConfigure(serial uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 9, Name: "xdg_positioner.set_parent_configure", Since: 3}, wl.ArgUint(serial)); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgPositioner) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_positioner and calls the registered handlers.
func (o *XdgPositioner) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// XdgSurfaceInterface is the protocol interface name.
const XdgSurfaceInterface = "xdg_surface"

// XdgSurface is the generated binding for xdg_surface version 7.
type XdgSurface struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu  sync.Mutex
	onConfigure []func(serial uint32)
}

// NewXdgSurface returns an unbound XdgSurface.
func NewXdgSurface(ctx *wl.Context) *XdgSurface {
	obj := &XdgSurface{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the xdg_surface object. An xdg_surface must only be destroyed after its role object has been destroyed, otherwise a defunct_role_object error is raised.
func (o *XdgSurface) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_surface.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// This creates an xdg_toplevel object for the given xdg_surface and gives the associated wl_surface the xdg_toplevel role. See the documentation of xdg_toplevel for more details about what an xdg_toplevel is and how it is used.
func (o *XdgSurface) GetToplevel() (*XdgToplevel, error) {
	child := &XdgToplevel{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_surface.get_toplevel", Child: child}, wl.ArgObject(child)); err != nil {
		return nil, err
	}
	return child, nil
}

// This creates an xdg_popup object for the given xdg_surface and gives the associated wl_surface the xdg_popup role. If null is passed as a parent, a parent surface must be specified using some other protocol, before committing the initial state. See the documentation of xdg_popup for more details about what an xdg_popup is and how it is used.
func (o *XdgSurface) GetPopup(parent *XdgSurface, positioner *XdgPositioner) (*XdgPopup, error) {
	var arg1 wl.Object
	if parent != nil {
		arg1 = parent
	}
	var arg2 wl.Object
	if positioner != nil {
		arg2 = positioner
	}
	child := &XdgPopup{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_surface.get_popup", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1), wl.ArgObject(arg2)); err != nil {
		return nil, err
	}
	return child, nil
}

// The window geometry of a surface is its "visible bounds" from the user's perspective. Client-side decorations often have invisible portions like drop-shadows which should be ignored for the purposes of aligning, placing and constraining windows. Note that in some situations, compositors may clip rendering to the window geometry, so the client should avoid putting functional elements outside of it. The window geometry is double-buffered state, see wl_surface.commit. When maintaining a position, the compositor should treat the (x, y) coordinate of the window geometry as the top left corner of the window. A client changing the (x, y) window geometry coordinate should in general not alter the position of the window. Once the window geometry of the surface is set, it is not possible to unset it, and it will remain the same until set_window_geometry is called again, even if a new subsurface or buffer is attached. If never set, the value is the full bounds of the surface, including any subsurfaces. This updates dynamically on every commit. This unset is meant for extremely simple clients. The arguments are given in the surface-local coordinate space of the wl_surface associated with this xdg_surface, and may extend outside of the wl_surface itself to mark parts of the subsurface tree as part of the window geometry. When applied, the effective window geometry will be the set window geometry clamped to the bounding rectangle of the combined geometry of the surface of the xdg_surface and the associated subsurfaces. The effective geometry will not be recalculated unless a new call to set_window_geometry is done and the new pending surface state is subsequently applied. The width and height of the effective window geometry must be greater than zero. Setting an invalid size will raise an invalid_size error.
func (o *XdgSurface) SetWindowGeometry(x int32, y int32, width int32, height int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "xdg_surface.set_window_geometry"}, wl.ArgInt(x), wl.ArgInt(y), wl.ArgInt(width), wl.ArgInt(height)); err != nil {
		return err
	}
	return nil
}

// When a configure event is received, if a client commits the surface in response to the configure event, then the client must make an ack_configure request sometime before the commit request, passing along the serial of the configure event. For instance, for toplevel surfaces the compositor might use this information to move a surface to the top left only when the client has drawn itself for the maximized or fullscreen state. If the client receives multiple configure events before it can respond to one, it only has to ack the last configure event. Acking a configure event that was never sent raises an invalid_serial error. A client is not required to commit immediately after sending an ack_configure request - it may even ack_configure several times before its next surface commit. A client may send multiple ack_configure requests before committing, but only the last request sent before a commit indicates which configure event the client really is responding to. Sending an ack_configure request consumes the serial number sent with the request, as well as serial numbers sent by all configure events sent on this xdg_surface prior to the configure event referenced by the committed serial. It is an error to issue multiple ack_configure requests referencing a serial from the same configure event, or to issue an ack_configure request referencing a serial from a configure event issued before the event identified by the last ack_configure request for the same xdg_surface. Doing so will raise an invalid_serial error.
func (o *XdgSurface) AckConfigure(serial uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "xdg_surface.ack_configure"}, wl.ArgUint(serial)); err != nil {
		return err
	}
	return nil
}

// OnConfigure registers a handler for the configure event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgSurface) OnConfigure(handler func(serial uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onConfigure = append(o.onConfigure, handler)
}

// handlersForConfigure returns the handlers registered for configure, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgSurface) handlersForConfigure() []func(serial uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onConfigure
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgSurface) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "uint,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_surface and calls the registered handlers.
func (o *XdgSurface) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // configure
		serial := event.Uint32()

		for i, handler := range o.handlersForConfigure() {
			_ = i
			handler(serial)
		}
	default:
	}
}

// XdgToplevelInterface is the protocol interface name.
const XdgToplevelInterface = "xdg_toplevel"

// XdgToplevel is the generated binding for xdg_toplevel version 7.
type XdgToplevel struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu        sync.Mutex
	onConfigure       []func(width int32, height int32, states []byte)
	onClose           []func()
	onConfigureBounds []func(width int32, height int32)
	onWmCapabilities  []func(capabilities []byte)
}

// NewXdgToplevel returns an unbound XdgToplevel.
func NewXdgToplevel(ctx *wl.Context) *XdgToplevel {
	obj := &XdgToplevel{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// This request destroys the role surface and unmaps the surface; see "Unmapping" behavior in interface section for details.
func (o *XdgToplevel) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_toplevel.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Set the "parent" of this surface. This surface should be stacked above the parent surface and all other ancestor surfaces. Parent surfaces should be set on dialogs, toolboxes, or other "auxiliary" surfaces, so that the parent is raised when the dialog is raised. Setting a null parent for a child surface unsets its parent. Setting a null parent for a surface which currently has no parent is a no-op. Only mapped surfaces can have child surfaces. Setting a parent which is not mapped is equivalent to setting a null parent. If a surface becomes unmapped, its children's parent is set to the parent of the now-unmapped surface. If the now-unmapped surface has no parent, its children's parent is unset. If the now-unmapped surface becomes mapped again, its parent-child relationship is not restored. The parent toplevel must not be one of the child toplevel's descendants, and the parent must be different from the child toplevel, otherwise the invalid_parent protocol error is raised.
func (o *XdgToplevel) SetParent(parent *XdgToplevel) error {
	var arg0 wl.Object
	if parent != nil {
		arg0 = parent
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_toplevel.set_parent"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// Set a short title for the surface. This string may be used to identify the surface in a task bar, window list, or other user interface elements provided by the compositor. The string must be encoded in UTF-8.
func (o *XdgToplevel) SetTitle(title string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_toplevel.set_title"}, wl.ArgString(title)); err != nil {
		return err
	}
	return nil
}

// Set an application identifier for the surface. The app ID identifies the general class of applications to which the surface belongs. The compositor can use this to group multiple surfaces together, or to determine how to launch a new application. For D-Bus activatable applications, the app ID is used as the D-Bus service name. The compositor shell will try to group application surfaces together by their app ID. As a best practice, it is suggested to select app ID's that match the basename of the application's .desktop file. For example, "org.freedesktop.FooViewer" where the .desktop file is "org.freedesktop.FooViewer.desktop". Like other properties, a set_app_id request can be sent after the xdg_toplevel has been mapped to update the property. See the desktop-entry specification [0] for more details on application identifiers and how they relate to well-known D-Bus names and .desktop files. [0] https://standards.freedesktop.org/desktop-entry-spec/
func (o *XdgToplevel) SetAppId(appId string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "xdg_toplevel.set_app_id"}, wl.ArgString(appId)); err != nil {
		return err
	}
	return nil
}

// Clients implementing client-side decorations might want to show a context menu when right-clicking on the decorations, giving the user a menu that they can use to maximize or minimize the window. This request asks the compositor to pop up such a window menu at the given position, relative to the local surface coordinates of the parent surface. There are no guarantees as to what menu items the window menu contains, or even if a window menu will be drawn at all. This request must be used in response to some sort of user action like a button press, key press, or touch down event.
func (o *XdgToplevel) ShowWindowMenu(seat *cross_wl_seat.Seat, serial uint32, x int32, y int32) error {
	var arg0 wl.Object
	if seat != nil {
		arg0 = seat
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "xdg_toplevel.show_window_menu"}, wl.ArgObject(arg0), wl.ArgUint(serial), wl.ArgInt(x), wl.ArgInt(y)); err != nil {
		return err
	}
	return nil
}

// Start an interactive, user-driven move of the surface. This request must be used in response to some sort of user action like a button press, key press, or touch down event. The passed serial is used to determine the type of interactive move (touch, pointer, etc). The server may ignore move requests depending on the state of the surface (e.g. fullscreen or maximized), or if the passed serial is no longer valid. If triggered, the surface will lose the focus of the device (wl_pointer, wl_touch, etc) used for the move. It is up to the compositor to visually indicate that the move is taking place, such as updating a pointer cursor, during the move. There is no guarantee that the device focus will return when the move is completed.
func (o *XdgToplevel) Move(seat *cross_wl_seat.Seat, serial uint32) error {
	var arg0 wl.Object
	if seat != nil {
		arg0 = seat
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 5, Name: "xdg_toplevel.move"}, wl.ArgObject(arg0), wl.ArgUint(serial)); err != nil {
		return err
	}
	return nil
}

// Start a user-driven, interactive resize of the surface. This request must be used in response to some sort of user action like a button press, key press, or touch down event. The passed serial is used to determine the type of interactive resize (touch, pointer, etc). The server may ignore resize requests depending on the state of the surface (e.g. fullscreen or maximized). If triggered, the client will receive configure events with the "resize" state enum value and the expected sizes. See the "resize" enum value for more details about what is required. The client must also acknowledge configure events using "ack_configure". After the resize is completed, the client will receive another "configure" event without the resize state. If triggered, the surface also will lose the focus of the device (wl_pointer, wl_touch, etc) used for the resize. It is up to the compositor to visually indicate that the resize is taking place, such as updating a pointer cursor, during the resize. There is no guarantee that the device focus will return when the resize is completed. The edges parameter specifies how the surface should be resized, and is one of the values of the resize_edge enum. Values not matching a variant of the enum will cause the invalid_resize_edge protocol error. The compositor may use this information to update the surface position for example when dragging the top left corner. The compositor may also use this information to adapt its behavior, e.g. choose an appropriate cursor image.
func (o *XdgToplevel) Resize(seat *cross_wl_seat.Seat, serial uint32, edges uint32) error {
	var arg0 wl.Object
	if seat != nil {
		arg0 = seat
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 6, Name: "xdg_toplevel.resize"}, wl.ArgObject(arg0), wl.ArgUint(serial), wl.ArgUint(edges)); err != nil {
		return err
	}
	return nil
}

// Set a maximum size for the window. The client can specify a maximum size so that the compositor does not try to configure the window beyond this size. The width and height arguments are in window geometry coordinates. See xdg_surface.set_window_geometry. Values set in this way are double-buffered, see wl_surface.commit. The compositor can use this information to allow or disallow different states like maximize or fullscreen and draw accurate animations. Similarly, a tiling window manager may use this information to place and resize client windows in a more effective way. The client should not rely on the compositor to obey the maximum size. The compositor may decide to ignore the values set by the client and request a larger size. If never set, or a value of zero in the request, means that the client has no expected maximum size in the given dimension. As a result, a client wishing to reset the maximum size to an unspecified state can use zero for width and height in the request. Requesting a maximum size to be smaller than the minimum size of a surface is illegal and will result in an invalid_size error. The width and height must be greater than or equal to zero. Using strictly negative values for width or height will result in an invalid_size error.
func (o *XdgToplevel) SetMaxSize(width int32, height int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 7, Name: "xdg_toplevel.set_max_size"}, wl.ArgInt(width), wl.ArgInt(height)); err != nil {
		return err
	}
	return nil
}

// Set a minimum size for the window. The client can specify a minimum size so that the compositor does not try to configure the window below this size. The width and height arguments are in window geometry coordinates. See xdg_surface.set_window_geometry. Values set in this way are double-buffered, see wl_surface.commit. The compositor can use this information to allow or disallow different states like maximize or fullscreen and draw accurate animations. Similarly, a tiling window manager may use this information to place and resize client windows in a more effective way. The client should not rely on the compositor to obey the minimum size. The compositor may decide to ignore the values set by the client and request a smaller size. If never set, or a value of zero in the request, means that the client has no expected minimum size in the given dimension. As a result, a client wishing to reset the minimum size to an unspecified state can use zero for width and height in the request. Requesting a minimum size to be larger than the maximum size of a surface is illegal and will result in an invalid_size error. The width and height must be greater than or equal to zero. Using strictly negative values for width and height will result in an invalid_size error.
func (o *XdgToplevel) SetMinSize(width int32, height int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 8, Name: "xdg_toplevel.set_min_size"}, wl.ArgInt(width), wl.ArgInt(height)); err != nil {
		return err
	}
	return nil
}

// Maximize the surface. After requesting that the surface should be maximized, the compositor will respond by emitting a configure event. Whether this configure actually sets the window maximized is subject to compositor policies. The client must then update its content, drawing in the configured state. The client must also acknowledge the configure when committing the new content (see ack_configure). It is up to the compositor to decide how and where to maximize the surface, for example which output and what region of the screen should be used. If the surface was already maximized, the compositor will still emit a configure event with the "maximized" state. If the surface is in a fullscreen state, this request has no direct effect. It may alter the state the surface is returned to when unmaximized unless overridden by the compositor.
func (o *XdgToplevel) SetMaximized() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 9, Name: "xdg_toplevel.set_maximized"}); err != nil {
		return err
	}
	return nil
}

// Unmaximize the surface. After requesting that the surface should be unmaximized, the compositor will respond by emitting a configure event. Whether this actually un-maximizes the window is subject to compositor policies. If available and applicable, the compositor will include the window geometry dimensions the window had prior to being maximized in the configure event. The client must then update its content, drawing it in the configured state. The client must also acknowledge the configure when committing the new content (see ack_configure). It is up to the compositor to position the surface after it was unmaximized; usually the position the surface had before maximizing, if applicable. If the surface was already not maximized, the compositor will still emit a configure event without the "maximized" state. If the surface is in a fullscreen state, this request has no direct effect. It may alter the state the surface is returned to when unmaximized unless overridden by the compositor.
func (o *XdgToplevel) UnsetMaximized() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 10, Name: "xdg_toplevel.unset_maximized"}); err != nil {
		return err
	}
	return nil
}

// Make the surface fullscreen. After requesting that the surface should be fullscreened, the compositor will respond by emitting a configure event. Whether the client is actually put into a fullscreen state is subject to compositor policies. The client must also acknowledge the configure when committing the new content (see ack_configure). The output passed by the request indicates the client's preference as to which display it should be set fullscreen on. If this value is NULL, it's up to the compositor to choose which display will be used to map this surface. If the surface doesn't cover the whole output, the compositor will position the surface in the center of the output and compensate with border fill covering the rest of the output. The content of the border fill is undefined, but should be assumed to be in some way that attempts to blend into the surrounding area (e.g. solid black). If the fullscreened surface is not opaque, the compositor must make sure that other screen content not part of the same surface tree (made up of subsurfaces, popups or similarly coupled surfaces) are not visible below the fullscreened surface.
func (o *XdgToplevel) SetFullscreen(output *cross_wl_output.Output) error {
	var arg0 wl.Object
	if output != nil {
		arg0 = output
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 11, Name: "xdg_toplevel.set_fullscreen"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// Make the surface no longer fullscreen. After requesting that the surface should be unfullscreened, the compositor will respond by emitting a configure event. Whether this actually removes the fullscreen state of the client is subject to compositor policies. Making a surface unfullscreen sets states for the surface based on the following: * the state(s) it may have had before becoming fullscreen * any state(s) decided by the compositor * any state(s) requested by the client while the surface was fullscreen The compositor may include the previous window geometry dimensions in the configure event, if applicable. The client must also acknowledge the configure when committing the new content (see ack_configure).
func (o *XdgToplevel) UnsetFullscreen() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 12, Name: "xdg_toplevel.unset_fullscreen"}); err != nil {
		return err
	}
	return nil
}

// Request that the compositor minimize your surface. There is no way to know if the surface is currently minimized, nor is there any way to unset minimization on this surface. If you are looking to throttle redrawing when minimized, please instead use the wl_surface.frame event for this, as this will also work with live previews on windows in Alt-Tab, Expose or similar compositor features.
func (o *XdgToplevel) SetMinimized() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 13, Name: "xdg_toplevel.set_minimized"}); err != nil {
		return err
	}
	return nil
}

// OnConfigure registers a handler for the configure event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgToplevel) OnConfigure(handler func(width int32, height int32, states []byte)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onConfigure = append(o.onConfigure, handler)
}

// handlersForConfigure returns the handlers registered for configure, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgToplevel) handlersForConfigure() []func(width int32, height int32, states []byte) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onConfigure
}

// OnClose registers a handler for the close event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgToplevel) OnClose(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onClose = append(o.onClose, handler)
}

// handlersForClose returns the handlers registered for close, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgToplevel) handlersForClose() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onClose
}

// OnConfigureBounds registers a handler for the configure_bounds event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgToplevel) OnConfigureBounds(handler func(width int32, height int32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onConfigureBounds = append(o.onConfigureBounds, handler)
}

// handlersForConfigureBounds returns the handlers registered for configure_bounds, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgToplevel) handlersForConfigureBounds() []func(width int32, height int32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onConfigureBounds
}

// OnWmCapabilities registers a handler for the wm_capabilities event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgToplevel) OnWmCapabilities(handler func(capabilities []byte)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onWmCapabilities = append(o.onWmCapabilities, handler)
}

// handlersForWmCapabilities returns the handlers registered for wm_capabilities, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgToplevel) handlersForWmCapabilities() []func(capabilities []byte) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onWmCapabilities
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgToplevel) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "int,int,array,", true
	case 1:
		return "", true
	case 2:
		return "int,int,", true
	case 3:
		return "array,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_toplevel and calls the registered handlers.
func (o *XdgToplevel) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // configure
		width := event.Int32()
		height := event.Int32()
		states := event.Array()

		for i, handler := range o.handlersForConfigure() {
			_ = i
			handler(width, height, states)
		}
	case 1: // close

		for i, handler := range o.handlersForClose() {
			_ = i
			handler()
		}
	case 2: // configure_bounds
		width := event.Int32()
		height := event.Int32()

		for i, handler := range o.handlersForConfigureBounds() {
			_ = i
			handler(width, height)
		}
	case 3: // wm_capabilities
		capabilities := event.Array()

		for i, handler := range o.handlersForWmCapabilities() {
			_ = i
			handler(capabilities)
		}
	default:
	}
}

// XdgPopupInterface is the protocol interface name.
const XdgPopupInterface = "xdg_popup"

// XdgPopup is the generated binding for xdg_popup version 7.
type XdgPopup struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu     sync.Mutex
	onConfigure    []func(x int32, y int32, width int32, height int32)
	onPopupDone    []func()
	onRepositioned []func(token uint32)
}

// NewXdgPopup returns an unbound XdgPopup.
func NewXdgPopup(ctx *wl.Context) *XdgPopup {
	obj := &XdgPopup{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// This destroys the popup. Explicitly destroying the xdg_popup object will also dismiss the popup, and unmap the surface. If this xdg_popup is not the "topmost" popup, the xdg_wm_base.not_the_topmost_popup protocol error will be sent.
func (o *XdgPopup) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_popup.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// This request makes the created popup take an explicit grab. An explicit grab will be dismissed when the user dismisses the popup, or when the client destroys the xdg_popup. This can be done by the user clicking outside the surface, using the keyboard, or even locking the screen through closing the lid or a timeout. If the compositor denies the grab, the popup will be immediately dismissed. This request must be used in response to some sort of user action like a button press, key press, or touch down event. The serial number of the event should be passed as 'serial'. The parent of a grabbing popup must either be an xdg_toplevel surface or another xdg_popup with an explicit grab. If the parent is another xdg_popup it means that the popups are nested, with this popup now being the topmost popup. Nested popups must be destroyed in the reverse order they were created in, e.g. the only popup you are allowed to destroy at all times is the topmost one. When compositors choose to dismiss a popup, they may dismiss every nested grabbing popup as well. When a compositor dismisses popups, it will follow the same dismissing order as required from the client. If the topmost grabbing popup is destroyed, the grab will be returned to the parent of the popup, if that parent previously had an explicit grab. If the parent is a grabbing popup which has already been dismissed, this popup will be immediately dismissed. If the parent is a popup that did not take an explicit grab, an error will be raised. During a popup grab, the client owning the grab will receive pointer and touch events for all their surfaces as normal (similar to an "owner-events" grab in X11 parlance), while the top most grabbing popup will always have keyboard focus.
func (o *XdgPopup) Grab(seat *cross_wl_seat.Seat, serial uint32) error {
	var arg0 wl.Object
	if seat != nil {
		arg0 = seat
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_popup.grab"}, wl.ArgObject(arg0), wl.ArgUint(serial)); err != nil {
		return err
	}
	return nil
}

// Reposition an already-mapped popup. The popup will be placed given the details in the passed xdg_positioner object, and a xdg_popup.repositioned followed by xdg_popup.configure and xdg_surface.configure will be emitted in response. Any parameters set by the previous positioner will be discarded. The passed token will be sent in the corresponding xdg_popup.repositioned event. The new popup position will not take effect until the corresponding configure event is acknowledged by the client. See xdg_popup.repositioned for details. The token itself is opaque, and has no other special meaning. If multiple reposition requests are sent, the compositor may skip all but the last one. If the popup is repositioned in response to a configure event for its parent, the client should send an xdg_positioner.set_parent_configure and possibly an xdg_positioner.set_parent_size request to allow the compositor to properly constrain the popup. If the popup is repositioned together with a parent that is being resized, but not in response to a configure event, the client should send an xdg_positioner.set_parent_size request.
func (o *XdgPopup) Reposition(positioner *XdgPositioner, token uint32) error {
	var arg0 wl.Object
	if positioner != nil {
		arg0 = positioner
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_popup.reposition", Since: 3}, wl.ArgObject(arg0), wl.ArgUint(token)); err != nil {
		return err
	}
	return nil
}

// OnConfigure registers a handler for the configure event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgPopup) OnConfigure(handler func(x int32, y int32, width int32, height int32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onConfigure = append(o.onConfigure, handler)
}

// handlersForConfigure returns the handlers registered for configure, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgPopup) handlersForConfigure() []func(x int32, y int32, width int32, height int32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onConfigure
}

// OnPopupDone registers a handler for the popup_done event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgPopup) OnPopupDone(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onPopupDone = append(o.onPopupDone, handler)
}

// handlersForPopupDone returns the handlers registered for popup_done, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgPopup) handlersForPopupDone() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onPopupDone
}

// OnRepositioned registers a handler for the repositioned event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgPopup) OnRepositioned(handler func(token uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onRepositioned = append(o.onRepositioned, handler)
}

// handlersForRepositioned returns the handlers registered for repositioned, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgPopup) handlersForRepositioned() []func(token uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onRepositioned
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgPopup) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "int,int,int,int,", true
	case 1:
		return "", true
	case 2:
		return "uint,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_popup and calls the registered handlers.
func (o *XdgPopup) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // configure
		x := event.Int32()
		y := event.Int32()
		width := event.Int32()
		height := event.Int32()

		for i, handler := range o.handlersForConfigure() {
			_ = i
			handler(x, y, width, height)
		}
	case 1: // popup_done

		for i, handler := range o.handlersForPopupDone() {
			_ = i
			handler()
		}
	case 2: // repositioned
		token := event.Uint32()

		for i, handler := range o.handlersForRepositioned() {
			_ = i
			handler(token)
		}
	default:
	}
}
