// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: wlr_foreign_toplevel_management_unstable_v1
// Source: wlr-foreign-toplevel-management-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2018 Ilia Bozhinov
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package foreigntoplevel

import (
	"sync"

	cross_wl_output "github.com/bnema/wlturbo/protocol/core"
	cross_wl_seat "github.com/bnema/wlturbo/protocol/core"
	cross_wl_surface "github.com/bnema/wlturbo/protocol/core"
	"github.com/bnema/wlturbo/wl"
)

// STATE_MAXIMIZED is the state maximized value.
const STATE_MAXIMIZED = 0

// STATE_MINIMIZED is the state minimized value.
const STATE_MINIMIZED = 1

// STATE_ACTIVATED is the state activated value.
const STATE_ACTIVATED = 2

// STATE_FULLSCREEN is the state fullscreen value.
const STATE_FULLSCREEN = 3

// ERROR_INVALID_RECTANGLE is the error invalid_rectangle value.
const ERROR_INVALID_RECTANGLE = 0

// ForeignToplevelManagerInterface is the protocol interface name.
const ForeignToplevelManagerInterface = "zwlr_foreign_toplevel_manager_v1"

// ForeignToplevelManager is the generated binding for zwlr_foreign_toplevel_manager_v1 version 3.
type ForeignToplevelManager struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onToplevel []func(toplevelObject *ForeignToplevelHandle)
	onFinished []func()
}

// NewForeignToplevelManager returns an unbound ForeignToplevelManager.
func NewForeignToplevelManager(ctx *wl.Context) *ForeignToplevelManager {
	obj := &ForeignToplevelManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Indicates the client no longer wishes to receive events for new toplevels. However the compositor may emit further toplevel_created events, until the finished event is emitted. The client must not send any more requests after this one.
func (o *ForeignToplevelManager) Stop() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_foreign_toplevel_manager_v1.stop"}); err != nil {
		return err
	}
	return nil
}

// OnToplevel registers a handler for the toplevel event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelManager) OnToplevel(handler func(toplevelObject *ForeignToplevelHandle)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onToplevel = append(o.onToplevel, handler)
}

// handlersForToplevel returns the handlers registered for toplevel, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelManager) handlersForToplevel() []func(toplevelObject *ForeignToplevelHandle) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onToplevel
}

// OnFinished registers a handler for the finished event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelManager) OnFinished(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onFinished = append(o.onFinished, handler)
}

// handlersForFinished returns the handlers registered for finished, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelManager) handlersForFinished() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onFinished
}

// EventSignature returns the declared event argument types in wire order.
func (o *ForeignToplevelManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "new_id,", true
	case 1:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_foreign_toplevel_manager_v1 and calls the registered handlers.
func (o *ForeignToplevelManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // toplevel
		toplevelID := event.Uint32()
		toplevelObject := &ForeignToplevelHandle{}
		toplevelObject.SetContext(o.Context())
		toplevelObject.SetID(toplevelID)
		toplevelObject.SetVersion(o.Version())
		o.Context().Register(toplevelObject)

		for i, handler := range o.handlersForToplevel() {
			_ = i
			handler(toplevelObject)
		}
	case 1: // finished

		for i, handler := range o.handlersForFinished() {
			_ = i
			handler()
		}
		o.Context().Unregister(o)
	default:
	}
}

// ForeignToplevelHandleInterface is the protocol interface name.
const ForeignToplevelHandleInterface = "zwlr_foreign_toplevel_handle_v1"

// ForeignToplevelHandle is the generated binding for zwlr_foreign_toplevel_handle_v1 version 3.
type ForeignToplevelHandle struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu    sync.Mutex
	onTitle       []func(title string)
	onAppId       []func(appId string)
	onOutputEnter []func(outputID uint32)
	onOutputLeave []func(outputID uint32)
	onState       []func(state []byte)
	onDone        []func()
	onClosed      []func()
	onParent      []func(parentID uint32)
}

// NewForeignToplevelHandle returns an unbound ForeignToplevelHandle.
func NewForeignToplevelHandle(ctx *wl.Context) *ForeignToplevelHandle {
	obj := &ForeignToplevelHandle{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Requests that the toplevel be maximized. If the maximized state actually changes, this will be indicated by the state event.
func (o *ForeignToplevelHandle) SetMaximized() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_foreign_toplevel_handle_v1.set_maximized"}); err != nil {
		return err
	}
	return nil
}

// Requests that the toplevel be unmaximized. If the maximized state actually changes, this will be indicated by the state event.
func (o *ForeignToplevelHandle) UnsetMaximized() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_foreign_toplevel_handle_v1.unset_maximized"}); err != nil {
		return err
	}
	return nil
}

// Requests that the toplevel be minimized. If the minimized state actually changes, this will be indicated by the state event.
func (o *ForeignToplevelHandle) SetMinimized() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "zwlr_foreign_toplevel_handle_v1.set_minimized"}); err != nil {
		return err
	}
	return nil
}

// Requests that the toplevel be unminimized. If the minimized state actually changes, this will be indicated by the state event.
func (o *ForeignToplevelHandle) UnsetMinimized() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "zwlr_foreign_toplevel_handle_v1.unset_minimized"}); err != nil {
		return err
	}
	return nil
}

// Request that this toplevel be activated on the given seat. There is no guarantee the toplevel will be actually activated.
func (o *ForeignToplevelHandle) Activate(seat *cross_wl_seat.Seat) error {
	var arg0 wl.Object
	if seat != nil {
		arg0 = seat
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "zwlr_foreign_toplevel_handle_v1.activate"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// Send a request to the toplevel to close itself. The compositor would typically use a shell-specific method to carry out this request, for example by sending the xdg_toplevel.close event. However, this gives no guarantees the toplevel will actually be destroyed. If and when this happens, the zwlr_foreign_toplevel_handle_v1.closed event will be emitted.
func (o *ForeignToplevelHandle) Close() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 5, Name: "zwlr_foreign_toplevel_handle_v1.close"}); err != nil {
		return err
	}
	return nil
}

// The rectangle of the surface specified in this request corresponds to the place where the app using this protocol represents the given toplevel. It can be used by the compositor as a hint for some operations, e.g minimizing. The client is however not required to set this, in which case the compositor is free to decide some default value. If the client specifies more than one rectangle, only the last one is considered. The dimensions are given in surface-local coordinates. Setting width=height=0 removes the already-set rectangle.
func (o *ForeignToplevelHandle) SetRectangle(surface *cross_wl_surface.Surface, x int32, y int32, width int32, height int32) error {
	var arg0 wl.Object
	if surface != nil {
		arg0 = surface
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 6, Name: "zwlr_foreign_toplevel_handle_v1.set_rectangle"}, wl.ArgObject(arg0), wl.ArgInt(x), wl.ArgInt(y), wl.ArgInt(width), wl.ArgInt(height)); err != nil {
		return err
	}
	return nil
}

// Destroys the zwlr_foreign_toplevel_handle_v1 object. This request should be called either when the client does not want to use the toplevel anymore or after the closed event to finalize the destruction of the object.
func (o *ForeignToplevelHandle) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 7, Name: "zwlr_foreign_toplevel_handle_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Requests that the toplevel be fullscreened on the given output. If the fullscreen state and/or the outputs the toplevel is visible on actually change, this will be indicated by the state and output_enter/leave events. The output parameter is only a hint to the compositor. Also, if output is NULL, the compositor should decide which output the toplevel will be fullscreened on, if at all.
func (o *ForeignToplevelHandle) SetFullscreen(output *cross_wl_output.Output) error {
	var arg0 wl.Object
	if output != nil {
		arg0 = output
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 8, Name: "zwlr_foreign_toplevel_handle_v1.set_fullscreen", Since: 2}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// Requests that the toplevel be unfullscreened. If the fullscreen state actually changes, this will be indicated by the state event.
func (o *ForeignToplevelHandle) UnsetFullscreen() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 9, Name: "zwlr_foreign_toplevel_handle_v1.unset_fullscreen", Since: 2}); err != nil {
		return err
	}
	return nil
}

// OnTitle registers a handler for the title event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnTitle(handler func(title string)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onTitle = append(o.onTitle, handler)
}

// handlersForTitle returns the handlers registered for title, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForTitle() []func(title string) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onTitle
}

// OnAppId registers a handler for the app_id event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnAppId(handler func(appId string)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onAppId = append(o.onAppId, handler)
}

// handlersForAppId returns the handlers registered for app_id, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForAppId() []func(appId string) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onAppId
}

// OnOutputEnter registers a handler for the output_enter event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnOutputEnter(handler func(outputID uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onOutputEnter = append(o.onOutputEnter, handler)
}

// handlersForOutputEnter returns the handlers registered for output_enter, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForOutputEnter() []func(outputID uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onOutputEnter
}

// OnOutputLeave registers a handler for the output_leave event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnOutputLeave(handler func(outputID uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onOutputLeave = append(o.onOutputLeave, handler)
}

// handlersForOutputLeave returns the handlers registered for output_leave, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForOutputLeave() []func(outputID uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onOutputLeave
}

// OnState registers a handler for the state event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnState(handler func(state []byte)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onState = append(o.onState, handler)
}

// handlersForState returns the handlers registered for state, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForState() []func(state []byte) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onState
}

// OnDone registers a handler for the done event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnDone(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onDone = append(o.onDone, handler)
}

// handlersForDone returns the handlers registered for done, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForDone() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onDone
}

// OnClosed registers a handler for the closed event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnClosed(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onClosed = append(o.onClosed, handler)
}

// handlersForClosed returns the handlers registered for closed, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForClosed() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onClosed
}

// OnParent registers a handler for the parent event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ForeignToplevelHandle) OnParent(handler func(parentID uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onParent = append(o.onParent, handler)
}

// handlersForParent returns the handlers registered for parent, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ForeignToplevelHandle) handlersForParent() []func(parentID uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onParent
}

// EventSignature returns the declared event argument types in wire order.
func (o *ForeignToplevelHandle) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "string,", true
	case 1:
		return "string,", true
	case 2:
		return "object,", true
	case 3:
		return "object,", true
	case 4:
		return "array,", true
	case 5:
		return "", true
	case 6:
		return "", true
	case 7:
		return "object,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_foreign_toplevel_handle_v1 and calls the registered handlers.
func (o *ForeignToplevelHandle) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // title
		title := event.String()

		for i, handler := range o.handlersForTitle() {
			_ = i
			handler(title)
		}
	case 1: // app_id
		appId := event.String()

		for i, handler := range o.handlersForAppId() {
			_ = i
			handler(appId)
		}
	case 2: // output_enter
		outputID := event.Uint32()

		for i, handler := range o.handlersForOutputEnter() {
			_ = i
			handler(outputID)
		}
	case 3: // output_leave
		outputID := event.Uint32()

		for i, handler := range o.handlersForOutputLeave() {
			_ = i
			handler(outputID)
		}
	case 4: // state
		state := event.Array()

		for i, handler := range o.handlersForState() {
			_ = i
			handler(state)
		}
	case 5: // done

		for i, handler := range o.handlersForDone() {
			_ = i
			handler()
		}
	case 6: // closed

		for i, handler := range o.handlersForClosed() {
			_ = i
			handler()
		}
	case 7: // parent
		parentID := event.Uint32()

		for i, handler := range o.handlersForParent() {
			_ = i
			handler(parentID)
		}
	default:
	}
}
