// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: pointer_constraints_unstable_v1
// Source: pointer-constraints-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2014      Jonas Ådahl
// Copyright © 2015      Red Hat Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package pointerconstraints

import (
	"sync"

	cross_wl_pointer "github.com/bnema/wlturbo/protocol/core"
	cross_wl_region "github.com/bnema/wlturbo/protocol/core"
	cross_wl_surface "github.com/bnema/wlturbo/protocol/core"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_ALREADY_CONSTRAINED is the error already_constrained value.
const ERROR_ALREADY_CONSTRAINED = 1

// LIFETIME_ONESHOT is the lifetime oneshot value.
const LIFETIME_ONESHOT = 1

// LIFETIME_PERSISTENT is the lifetime persistent value.
const LIFETIME_PERSISTENT = 2

// PointerConstraintsInterface is the protocol interface name.
const PointerConstraintsInterface = "zwp_pointer_constraints_v1"

// PointerConstraints is the generated binding for zwp_pointer_constraints_v1 version 1.
type PointerConstraints struct {
	wl.BaseProxy
}

// NewPointerConstraints returns an unbound PointerConstraints.
func NewPointerConstraints(ctx *wl.Context) *PointerConstraints {
	obj := &PointerConstraints{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Used by the client to notify the server that it will no longer use this pointer constraints object.
func (o *PointerConstraints) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwp_pointer_constraints_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// The lock_pointer request lets the client request to disable movements of the virtual pointer (i.e. the cursor), effectively locking the pointer to a position. This request may not take effect immediately; in the future, when the compositor deems implementation-specific constraints are satisfied, the pointer lock will be activated and the compositor sends a locked event. The protocol provides no guarantee that the constraints are ever satisfied, and does not require the compositor to send an error if the constraints cannot ever be satisfied. It is thus possible to request a lock that will never activate. There may not be another pointer constraint of any kind requested or active on the surface for any of the wl_pointer objects of the seat of the passed pointer when requesting a lock. If there is, an error will be raised. See general pointer lock documentation for more details. The intersection of the region passed with this request and the input region of the surface is used to determine where the pointer must be in order for the lock to activate. It is up to the compositor whether to warp the pointer or require some kind of user interaction for the lock to activate. If the region is null the surface input region is used. A surface may receive pointer focus without the lock being activated. The request creates a new object wp_locked_pointer which is used to interact with the lock as well as receive updates about its state. See the the description of wp_locked_pointer for further information. Note that while a pointer is locked, the wl_pointer objects of the corresponding seat will not emit any wl_pointer.motion events, but relative motion events will still be emitted via wp_relative_pointer objects of the same seat. wl_pointer.axis and wl_pointer.button events are unaffected.
func (o *PointerConstraints) LockPointer(surface *cross_wl_surface.Surface, pointer *cross_wl_pointer.Pointer, region *cross_wl_region.Region, lifetime uint32) (*LockedPointer, error) {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	var arg2 wl.Object
	if pointer != nil {
		arg2 = pointer
	}
	var arg3 wl.Object
	if region != nil {
		arg3 = region
	}
	child := &LockedPointer{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwp_pointer_constraints_v1.lock_pointer", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1), wl.ArgObject(arg2), wl.ArgObject(arg3), wl.ArgUint(lifetime)); err != nil {
		return nil, err
	}
	return child, nil
}

// The confine_pointer request lets the client request to confine the pointer cursor to a given region. This request may not take effect immediately; in the future, when the compositor deems implementation- specific constraints are satisfied, the pointer confinement will be activated and the compositor sends a confined event. The intersection of the region passed with this request and the input region of the surface is used to determine where the pointer must be in order for the confinement to activate. It is up to the compositor whether to warp the pointer or require some kind of user interaction for the confinement to activate. If the region is null the surface input region is used. The request will create a new object wp_confined_pointer which is used to interact with the confinement as well as receive updates about its state. See the the description of wp_confined_pointer for further information.
func (o *PointerConstraints) ConfinePointer(surface *cross_wl_surface.Surface, pointer *cross_wl_pointer.Pointer, region *cross_wl_region.Region, lifetime uint32) (*ConfinedPointer, error) {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	var arg2 wl.Object
	if pointer != nil {
		arg2 = pointer
	}
	var arg3 wl.Object
	if region != nil {
		arg3 = region
	}
	child := &ConfinedPointer{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "zwp_pointer_constraints_v1.confine_pointer", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1), wl.ArgObject(arg2), wl.ArgObject(arg3), wl.ArgUint(lifetime)); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *PointerConstraints) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_pointer_constraints_v1 and calls the registered handlers.
func (o *PointerConstraints) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// LockedPointerInterface is the protocol interface name.
const LockedPointerInterface = "zwp_locked_pointer_v1"

// LockedPointer is the generated binding for zwp_locked_pointer_v1 version 1.
type LockedPointer struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onLocked   []func()
	onUnlocked []func()
}

// NewLockedPointer returns an unbound LockedPointer.
func NewLockedPointer(ctx *wl.Context) *LockedPointer {
	obj := &LockedPointer{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the locked pointer object. If applicable, the compositor will unlock the pointer.
func (o *LockedPointer) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwp_locked_pointer_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Set the cursor position hint relative to the top left corner of the surface. If the client is drawing its own cursor, it should update the position hint to the position of its own cursor. A compositor may use this information to warp the pointer upon unlock in order to avoid pointer jumps. The cursor position hint is double-buffered state, see wl_surface.commit.
func (o *LockedPointer) SetCursorPositionHint(surfaceX wl.Fixed, surfaceY wl.Fixed) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwp_locked_pointer_v1.set_cursor_position_hint"}, wl.ArgFixed(surfaceX), wl.ArgFixed(surfaceY)); err != nil {
		return err
	}
	return nil
}

// Set a new region used to lock the pointer. The new lock region is double-buffered, see wl_surface.commit. For details about the lock region, see wp_locked_pointer.
func (o *LockedPointer) SetRegion(region *cross_wl_region.Region) error {
	var arg0 wl.Object
	if region != nil {
		arg0 = region
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "zwp_locked_pointer_v1.set_region"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// OnLocked registers a handler for the locked event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *LockedPointer) OnLocked(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onLocked = append(o.onLocked, handler)
}

// handlersForLocked returns the handlers registered for locked, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *LockedPointer) handlersForLocked() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onLocked
}

// OnUnlocked registers a handler for the unlocked event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *LockedPointer) OnUnlocked(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onUnlocked = append(o.onUnlocked, handler)
}

// handlersForUnlocked returns the handlers registered for unlocked, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *LockedPointer) handlersForUnlocked() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onUnlocked
}

// EventSignature returns the declared event argument types in wire order.
func (o *LockedPointer) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "", true
	case 1:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_locked_pointer_v1 and calls the registered handlers.
func (o *LockedPointer) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // locked

		for i, handler := range o.handlersForLocked() {
			_ = i
			handler()
		}
	case 1: // unlocked

		for i, handler := range o.handlersForUnlocked() {
			_ = i
			handler()
		}
	default:
	}
}

// ConfinedPointerInterface is the protocol interface name.
const ConfinedPointerInterface = "zwp_confined_pointer_v1"

// ConfinedPointer is the generated binding for zwp_confined_pointer_v1 version 1.
type ConfinedPointer struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu   sync.Mutex
	onConfined   []func()
	onUnconfined []func()
}

// NewConfinedPointer returns an unbound ConfinedPointer.
func NewConfinedPointer(ctx *wl.Context) *ConfinedPointer {
	obj := &ConfinedPointer{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the confined pointer object. If applicable, the compositor will unconfine the pointer.
func (o *ConfinedPointer) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwp_confined_pointer_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Set a new region used to confine the pointer. The new confine region is double-buffered, see wl_surface.commit. If the confinement is active when the new confinement region is applied and the pointer ends up outside of newly applied region, the pointer may warped to a position within the new confinement region. If warped, a wl_pointer.motion event will be emitted, but no wp_relative_pointer.relative_motion event. The compositor may also, instead of using the new region, unconfine the pointer. For details about the confine region, see wp_confined_pointer.
func (o *ConfinedPointer) SetRegion(region *cross_wl_region.Region) error {
	var arg0 wl.Object
	if region != nil {
		arg0 = region
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwp_confined_pointer_v1.set_region"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// OnConfined registers a handler for the confined event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ConfinedPointer) OnConfined(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onConfined = append(o.onConfined, handler)
}

// handlersForConfined returns the handlers registered for confined, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ConfinedPointer) handlersForConfined() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onConfined
}

// OnUnconfined registers a handler for the unconfined event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ConfinedPointer) OnUnconfined(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onUnconfined = append(o.onUnconfined, handler)
}

// handlersForUnconfined returns the handlers registered for unconfined, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ConfinedPointer) handlersForUnconfined() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onUnconfined
}

// EventSignature returns the declared event argument types in wire order.
func (o *ConfinedPointer) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "", true
	case 1:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_confined_pointer_v1 and calls the registered handlers.
func (o *ConfinedPointer) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // confined

		for i, handler := range o.handlersForConfined() {
			_ = i
			handler()
		}
	case 1: // unconfined

		for i, handler := range o.handlersForUnconfined() {
			_ = i
			handler()
		}
	default:
	}
}
