// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: xdg_decoration_unstable_v1
// Source: xdg-decoration-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2018 Simon Ser
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgdecoration

import (
	"sync"

	cross_xdg_toplevel "github.com/bnema/wlturbo/protocol/xdgshell"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_UNCONFIGURED_BUFFER is the error unconfigured_buffer value.
const ERROR_UNCONFIGURED_BUFFER = 0

// ERROR_ALREADY_CONSTRUCTED is the error already_constructed value.
const ERROR_ALREADY_CONSTRUCTED = 1

// ERROR_ORPHANED is the error orphaned value.
const ERROR_ORPHANED = 2

// ERROR_INVALID_MODE is the error invalid_mode value.
const ERROR_INVALID_MODE = 3

// MODE_CLIENT_SIDE is the mode client_side value.
const MODE_CLIENT_SIDE = 1

// MODE_SERVER_SIDE is the mode server_side value.
const MODE_SERVER_SIDE = 2

// ZxdgDecorationManagerInterface is the protocol interface name.
const ZxdgDecorationManagerInterface = "zxdg_decoration_manager_v1"

// ZxdgDecorationManager is the generated binding for zxdg_decoration_manager_v1 version 2.
type ZxdgDecorationManager struct {
	wl.BaseProxy
}

// NewZxdgDecorationManager returns an unbound ZxdgDecorationManager.
func NewZxdgDecorationManager(ctx *wl.Context) *ZxdgDecorationManager {
	obj := &ZxdgDecorationManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the decoration manager. This doesn't destroy objects created with the manager.
func (o *ZxdgDecorationManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zxdg_decoration_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Create a new decoration object associated with the given toplevel. For objects of version 1, creating an xdg_toplevel_decoration from an xdg_toplevel which has a buffer attached or committed is a client error, and any attempts by a client to attach or manipulate a buffer prior to the first xdg_toplevel_decoration.configure event must also be treated as errors. For objects of version 2 or newer, creating an xdg_toplevel_decoration from an xdg_toplevel which has a buffer attached or committed is allowed. The initial decoration mode of the surface if a buffer is already attached depends on whether a xdg_toplevel_decoration object has been associated with the surface or not prior to this request. If an xdg_toplevel_decoration was associated with the surface, then destroyed without a surface commit, the previous decoration mode is retained. If no xdg_toplevel_decoration was associated with the surface prior to this request, or if a surface commit has been performed after a previous xdg_toplevel_decoration object associated with the surface was destroyed, the decoration mode is assumed to be client-side.
func (o *ZxdgDecorationManager) GetToplevelDecoration(toplevel *cross_xdg_toplevel.XdgToplevel) (*ZxdgToplevelDecoration, error) {
	var arg1 wl.Object
	if toplevel != nil {
		arg1 = toplevel
	}
	child := &ZxdgToplevelDecoration{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zxdg_decoration_manager_v1.get_toplevel_decoration", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1)); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *ZxdgDecorationManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zxdg_decoration_manager_v1 and calls the registered handlers.
func (o *ZxdgDecorationManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// ZxdgToplevelDecorationInterface is the protocol interface name.
const ZxdgToplevelDecorationInterface = "zxdg_toplevel_decoration_v1"

// ZxdgToplevelDecoration is the generated binding for zxdg_toplevel_decoration_v1 version 2.
type ZxdgToplevelDecoration struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu  sync.Mutex
	onConfigure []func(mode uint32)
}

// NewZxdgToplevelDecoration returns an unbound ZxdgToplevelDecoration.
func NewZxdgToplevelDecoration(ctx *wl.Context) *ZxdgToplevelDecoration {
	obj := &ZxdgToplevelDecoration{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Switch back to a mode without any server-side decorations at the next commit, unless a new xdg_toplevel_decoration is created for the surface first.
func (o *ZxdgToplevelDecoration) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zxdg_toplevel_decoration_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Set the toplevel surface decoration mode. This informs the compositor that the client prefers the provided decoration mode. After requesting a decoration mode, the compositor will respond by emitting an xdg_surface.configure event. The client should then update its content, drawing it without decorations if the received mode is server-side decorations. The client must also acknowledge the configure when committing the new content (see xdg_surface.ack_configure). The compositor can decide not to use the client's mode and enforce a different mode instead. Clients whose decoration mode depend on the xdg_toplevel state may send a set_mode request in response to an xdg_surface.configure event and wait for the next xdg_surface.configure event to prevent unwanted state. Such clients are responsible for preventing configure loops and must make sure not to send multiple successive set_mode requests with the same decoration mode. If an invalid mode is supplied by the client, the invalid_mode protocol error is raised by the compositor.
func (o *ZxdgToplevelDecoration) SetMode(mode uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zxdg_toplevel_decoration_v1.set_mode"}, wl.ArgUint(mode)); err != nil {
		return err
	}
	return nil
}

// Unset the toplevel surface decoration mode. This informs the compositor that the client doesn't prefer a particular decoration mode. This request has the same semantics as set_mode.
func (o *ZxdgToplevelDecoration) UnsetMode() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "zxdg_toplevel_decoration_v1.unset_mode"}); err != nil {
		return err
	}
	return nil
}

// OnConfigure registers a handler for the configure event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ZxdgToplevelDecoration) OnConfigure(handler func(mode uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onConfigure = append(o.onConfigure, handler)
}

// handlersForConfigure returns the handlers registered for configure, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ZxdgToplevelDecoration) handlersForConfigure() []func(mode uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onConfigure
}

// EventSignature returns the declared event argument types in wire order.
func (o *ZxdgToplevelDecoration) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "uint,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zxdg_toplevel_decoration_v1 and calls the registered handlers.
func (o *ZxdgToplevelDecoration) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // configure
		mode := event.Uint32()

		for i, handler := range o.handlersForConfigure() {
			_ = i
			handler(mode)
		}
	default:
	}
}
