// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: xdg_activation_v1
// Source: xdg-activation-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2020 Aleix Pol Gonzalez <aleixpol@kde.org>
// Copyright © 2020 Carlos Garnacho <carlosg@gnome.org>
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package xdgactivation

import (
	"sync"

	cross_wl_seat "github.com/bnema/wlturbo/protocol/core"
	cross_wl_surface "github.com/bnema/wlturbo/protocol/core"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_ALREADY_USED is the error already_used value.
const ERROR_ALREADY_USED = 0

// XdgActivationInterface is the protocol interface name.
const XdgActivationInterface = "xdg_activation_v1"

// XdgActivation is the generated binding for xdg_activation_v1 version 1.
type XdgActivation struct {
	wl.BaseProxy
}

// NewXdgActivation returns an unbound XdgActivation.
func NewXdgActivation(ctx *wl.Context) *XdgActivation {
	obj := &XdgActivation{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Notify the compositor that the xdg_activation object will no longer be used. The child objects created via this interface are unaffected and should be destroyed separately.
func (o *XdgActivation) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_activation_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Creates an xdg_activation_token_v1 object that will provide the initiating client with a unique token for this activation. This token should be offered to the clients to be activated.
func (o *XdgActivation) GetActivationToken() (*XdgActivationToken, error) {
	child := &XdgActivationToken{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_activation_v1.get_activation_token", Child: child}, wl.ArgObject(child)); err != nil {
		return nil, err
	}
	return child, nil
}

// Requests surface activation. It's up to the compositor to display this information as desired, for example by placing the surface above the rest. The compositor may know who requested this by checking the activation token and might decide not to follow through with the activation if it's considered unwanted. Compositors can ignore unknown activation tokens when an invalid token is passed.
func (o *XdgActivation) Activate(token string, surface *cross_wl_surface.Surface) error {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_activation_v1.activate"}, wl.ArgString(token), wl.ArgObject(arg1)); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgActivation) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_activation_v1 and calls the registered handlers.
func (o *XdgActivation) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// XdgActivationTokenInterface is the protocol interface name.
const XdgActivationTokenInterface = "xdg_activation_token_v1"

// XdgActivationToken is the generated binding for xdg_activation_token_v1 version 1.
type XdgActivationToken struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu sync.Mutex
	onDone     []func(token string)
}

// NewXdgActivationToken returns an unbound XdgActivationToken.
func NewXdgActivationToken(ctx *wl.Context) *XdgActivationToken {
	obj := &XdgActivationToken{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Provides information about the seat and serial event that requested the token. The serial can come from an input or focus event. For instance, if a click triggers the launch of a third-party client, the launcher client should send a set_serial request with the serial and seat from the wl_pointer.button event. Some compositors might refuse to activate toplevels when the token doesn't have a valid and recent enough event serial. Must be sent before commit. This information is optional.
func (o *XdgActivationToken) SetSerial(serial uint32, seat *cross_wl_seat.Seat) error {
	var arg1 wl.Object
	if seat != nil {
		arg1 = seat
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "xdg_activation_token_v1.set_serial"}, wl.ArgUint(serial), wl.ArgObject(arg1)); err != nil {
		return err
	}
	return nil
}

// The requesting client can specify an app_id to associate the token being created with it. Must be sent before commit. This information is optional.
func (o *XdgActivationToken) SetAppId(appId string) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "xdg_activation_token_v1.set_app_id"}, wl.ArgString(appId)); err != nil {
		return err
	}
	return nil
}

// This request sets the surface requesting the activation. Note, this is different from the surface that will be activated. Some compositors might refuse to activate toplevels when the token doesn't have a requesting surface. Must be sent before commit. This information is optional.
func (o *XdgActivationToken) SetSurface(surface *cross_wl_surface.Surface) error {
	var arg0 wl.Object
	if surface != nil {
		arg0 = surface
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "xdg_activation_token_v1.set_surface"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// Requests an activation token based on the different parameters that have been offered through set_serial, set_surface and set_app_id.
func (o *XdgActivationToken) Commit() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "xdg_activation_token_v1.commit"}); err != nil {
		return err
	}
	return nil
}

// Notify the compositor that the xdg_activation_token_v1 object will no longer be used. The received token stays valid.
func (o *XdgActivationToken) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "xdg_activation_token_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// OnDone registers a handler for the done event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *XdgActivationToken) OnDone(handler func(token string)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onDone = append(o.onDone, handler)
}

// handlersForDone returns the handlers registered for done, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *XdgActivationToken) handlersForDone() []func(token string) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onDone
}

// EventSignature returns the declared event argument types in wire order.
func (o *XdgActivationToken) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "string,", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on xdg_activation_token_v1 and calls the registered handlers.
func (o *XdgActivationToken) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // done
		token := event.String()

		for i, handler := range o.handlersForDone() {
			_ = i
			handler(token)
		}
	default:
	}
}
