// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: wlr_layer_shell_unstable_v1
// Source: wlr-layer-shell-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2017 Drew DeVault
//
// Permission to use, copy, modify, distribute, and sell this
// software and its documentation for any purpose is hereby granted
// without fee, provided that the above copyright notice appear in
// all copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// the copyright holders not be used in advertising or publicity
// pertaining to distribution of the software without specific,
// written prior permission.  The copyright holders make no
// representations about the suitability of this software for any
// purpose.  It is provided "as is" without express or implied
// warranty.
//
// THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
// SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
// SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
// AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
// ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
// THIS SOFTWARE.

package layershell

import (
	"sync"

	cross_wl_output "github.com/bnema/wlturbo/protocol/core"
	cross_wl_surface "github.com/bnema/wlturbo/protocol/core"
	cross_xdg_popup "github.com/bnema/wlturbo/protocol/xdgshell"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_ROLE is the error role value.
const ERROR_ROLE = 0

// ERROR_INVALID_LAYER is the error invalid_layer value.
const ERROR_INVALID_LAYER = 1

// ERROR_ALREADY_CONSTRUCTED is the error already_constructed value.
const ERROR_ALREADY_CONSTRUCTED = 2

// LAYER_BACKGROUND is the layer background value.
const LAYER_BACKGROUND = 0

// LAYER_BOTTOM is the layer bottom value.
const LAYER_BOTTOM = 1

// LAYER_TOP is the layer top value.
const LAYER_TOP = 2

// LAYER_OVERLAY is the layer overlay value.
const LAYER_OVERLAY = 3

// KEYBOARD_INTERACTIVITY_NONE is the keyboard_interactivity none value.
const KEYBOARD_INTERACTIVITY_NONE = 0

// KEYBOARD_INTERACTIVITY_EXCLUSIVE is the keyboard_interactivity exclusive value.
const KEYBOARD_INTERACTIVITY_EXCLUSIVE = 1

// KEYBOARD_INTERACTIVITY_ON_DEMAND is the keyboard_interactivity on_demand value.
const KEYBOARD_INTERACTIVITY_ON_DEMAND = 2

// ERROR_INVALID_SURFACE_STATE is the error invalid_surface_state value.
const ERROR_INVALID_SURFACE_STATE = 0

// ERROR_INVALID_SIZE is the error invalid_size value.
const ERROR_INVALID_SIZE = 1

// ERROR_INVALID_ANCHOR is the error invalid_anchor value.
const ERROR_INVALID_ANCHOR = 2

// ERROR_INVALID_KEYBOARD_INTERACTIVITY is the error invalid_keyboard_interactivity value.
const ERROR_INVALID_KEYBOARD_INTERACTIVITY = 3

// ERROR_INVALID_EXCLUSIVE_EDGE is the error invalid_exclusive_edge value.
const ERROR_INVALID_EXCLUSIVE_EDGE = 4

// ANCHOR_TOP is the anchor top value.
const ANCHOR_TOP = 1

// ANCHOR_BOTTOM is the anchor bottom value.
const ANCHOR_BOTTOM = 2

// ANCHOR_LEFT is the anchor left value.
const ANCHOR_LEFT = 4

// ANCHOR_RIGHT is the anchor right value.
const ANCHOR_RIGHT = 8

// LayerShellInterface is the protocol interface name.
const LayerShellInterface = "zwlr_layer_shell_v1"

// LayerShell is the generated binding for zwlr_layer_shell_v1 version 5.
type LayerShell struct {
	wl.BaseProxy
}

// NewLayerShell returns an unbound LayerShell.
func NewLayerShell(ctx *wl.Context) *LayerShell {
	obj := &LayerShell{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Create a layer surface for an existing surface. This assigns the role of layer_surface, or raises a protocol error if another role is already assigned. Creating a layer surface from a wl_surface which has a buffer attached or committed is a client error, and any attempts by a client to attach or manipulate a buffer prior to the first layer_surface.configure call must also be treated as errors. After creating a layer_surface object and setting it up, the client must perform an initial commit without any buffer attached. The compositor will reply with a layer_surface.configure event. The client must acknowledge it and is then allowed to attach a buffer to map the surface. You may pass NULL for output to allow the compositor to decide which output to use. Generally this will be the one that the user most recently interacted with. Clients can specify a namespace that defines the purpose of the layer surface.
func (o *LayerShell) GetLayerSurface(surface *cross_wl_surface.Surface, output *cross_wl_output.Output, layer uint32, namespace string) (*LayerSurface, error) {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	var arg2 wl.Object
	if output != nil {
		arg2 = output
	}
	child := &LayerSurface{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_layer_shell_v1.get_layer_surface", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1), wl.ArgObject(arg2), wl.ArgUint(layer), wl.ArgString(namespace)); err != nil {
		return nil, err
	}
	return child, nil
}

// This request indicates that the client will not use the layer_shell object any more. Objects that have been created through this instance are not affected.
func (o *LayerShell) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_layer_shell_v1.destroy", Since: 3, Destructor: true}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *LayerShell) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_layer_shell_v1 and calls the registered handlers.
func (o *LayerShell) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// LayerSurfaceInterface is the protocol interface name.
const LayerSurfaceInterface = "zwlr_layer_surface_v1"

// LayerSurface is the generated binding for zwlr_layer_surface_v1 version 5.
type LayerSurface struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu  sync.Mutex
	onConfigure []func(serial uint32, width uint32, height uint32)
	onClosed    []func()
}

// NewLayerSurface returns an unbound LayerSurface.
func NewLayerSurface(ctx *wl.Context) *LayerSurface {
	obj := &LayerSurface{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Sets the size of the surface in surface-local coordinates. The compositor will display the surface centered with respect to its anchors. If you pass 0 for either value, the compositor will assign it and inform you of the assignment in the configure event. You must set your anchor to opposite edges in the dimensions you omit; not doing so is a protocol error. Both values are 0 by default. Size is double-buffered, see wl_surface.commit.
func (o *LayerSurface) SetSize(width uint32, height uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_layer_surface_v1.set_size"}, wl.ArgUint(width), wl.ArgUint(height)); err != nil {
		return err
	}
	return nil
}

// Requests that the compositor anchor the surface to the specified edges and corners. If two orthogonal edges are specified (e.g. 'top' and 'left'), then the anchor point will be the intersection of the edges (e.g. the top left corner of the output); otherwise the anchor point will be centered on that edge, or in the center if none is specified. Anchor is double-buffered, see wl_surface.commit.
func (o *LayerSurface) SetAnchor(anchor uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_layer_surface_v1.set_anchor"}, wl.ArgUint(anchor)); err != nil {
		return err
	}
	return nil
}

// Requests that the compositor avoids occluding an area with other surfaces. The compositor's use of this information is implementation-dependent - do not assume that this region will not actually be occluded. A positive value is only meaningful if the surface is anchored to one edge or an edge and both perpendicular edges. If the surface is not anchored, anchored to only two perpendicular edges (a corner), anchored to only two parallel edges or anchored to all edges, a positive value will be treated the same as zero. A positive zone is the distance from the edge in surface-local coordinates to consider exclusive. Surfaces that do not wish to have an exclusive zone may instead specify how they should interact with surfaces that do. If set to zero, the surface indicates that it would like to be moved to avoid occluding surfaces with a positive exclusive zone. If set to -1, the surface indicates that it would not like to be moved to accommodate for other surfaces, and the compositor should extend it all the way to the edges it is anchored to. For example, a panel might set its exclusive zone to 10, so that maximized shell surfaces are not shown on top of it. A notification might set its exclusive zone to 0, so that it is moved to avoid occluding the panel, but shell surfaces are shown underneath it. A wallpaper or lock screen might set their exclusive zone to -1, so that they stretch below or over the panel. The default value is 0. Exclusive zone is double-buffered, see wl_surface.commit.
func (o *LayerSurface) SetExclusiveZone(zone int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "zwlr_layer_surface_v1.set_exclusive_zone"}, wl.ArgInt(zone)); err != nil {
		return err
	}
	return nil
}

// Requests that the surface be placed some distance away from the anchor point on the output, in surface-local coordinates. Setting this value for edges you are not anchored to has no effect. The exclusive zone includes the margin. Margin is double-buffered, see wl_surface.commit.
func (o *LayerSurface) SetMargin(top int32, right int32, bottom int32, left int32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 3, Name: "zwlr_layer_surface_v1.set_margin"}, wl.ArgInt(top), wl.ArgInt(right), wl.ArgInt(bottom), wl.ArgInt(left)); err != nil {
		return err
	}
	return nil
}

// Set how keyboard events are delivered to this surface. By default, layer shell surfaces do not receive keyboard events; this request can be used to change this. This setting is inherited by child surfaces set by the get_popup request. Layer surfaces receive pointer, touch, and tablet events normally. If you do not want to receive them, set the input region on your surface to an empty region. Keyboard interactivity is double-buffered, see wl_surface.commit.
func (o *LayerSurface) SetKeyboardInteractivity(keyboardInteractivity uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 4, Name: "zwlr_layer_surface_v1.set_keyboard_interactivity"}, wl.ArgUint(keyboardInteractivity)); err != nil {
		return err
	}
	return nil
}

// This assigns an xdg_popup's parent to this layer_surface.  This popup should have been created via xdg_surface::get_popup with the parent set to NULL, and this request must be invoked before committing the popup's initial state. See the documentation of xdg_popup for more details about what an xdg_popup is and how it is used.
func (o *LayerSurface) GetPopup(popup *cross_xdg_popup.XdgPopup) error {
	var arg0 wl.Object
	if popup != nil {
		arg0 = popup
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 5, Name: "zwlr_layer_surface_v1.get_popup"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// When a configure event is received, if a client commits the surface in response to the configure event, then the client must make an ack_configure request sometime before the commit request, passing along the serial of the configure event. If the client receives multiple configure events before it can respond to one, it only has to ack the last configure event. A client is not required to commit immediately after sending an ack_configure request - it may even ack_configure several times before its next surface commit. A client may send multiple ack_configure requests before committing, but only the last request sent before a commit indicates which configure event the client really is responding to.
func (o *LayerSurface) AckConfigure(serial uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 6, Name: "zwlr_layer_surface_v1.ack_configure"}, wl.ArgUint(serial)); err != nil {
		return err
	}
	return nil
}

// This request destroys the layer surface.
func (o *LayerSurface) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 7, Name: "zwlr_layer_surface_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Change the layer that the surface is rendered on. Layer is double-buffered, see wl_surface.commit.
func (o *LayerSurface) SetLayer(layer uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 8, Name: "zwlr_layer_surface_v1.set_layer", Since: 2}, wl.ArgUint(layer)); err != nil {
		return err
	}
	return nil
}

// Requests an edge for the exclusive zone to apply. The exclusive edge will be automatically deduced from anchor points when possible, but when the surface is anchored to a corner, it will be necessary to set it explicitly to disambiguate, as it is not possible to deduce which one of the two corner edges should be used. The edge must be one the surface is anchored to, otherwise the invalid_exclusive_edge protocol error will be raised.
func (o *LayerSurface) SetExclusiveEdge(edge uint32) error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 9, Name: "zwlr_layer_surface_v1.set_exclusive_edge", Since: 5}, wl.ArgUint(edge)); err != nil {
		return err
	}
	return nil
}

// OnConfigure registers a handler for the configure event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *LayerSurface) OnConfigure(handler func(serial uint32, width uint32, height uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onConfigure = append(o.onConfigure, handler)
}

// handlersForConfigure returns the handlers registered for configure, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *LayerSurface) handlersForConfigure() []func(serial uint32, width uint32, height uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onConfigure
}

// OnClosed registers a handler for the closed event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *LayerSurface) OnClosed(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onClosed = append(o.onClosed, handler)
}

// handlersForClosed returns the handlers registered for closed, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *LayerSurface) handlersForClosed() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onClosed
}

// EventSignature returns the declared event argument types in wire order.
func (o *LayerSurface) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "uint,uint,uint,", true
	case 1:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_layer_surface_v1 and calls the registered handlers.
func (o *LayerSurface) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // configure
		serial := event.Uint32()
		width := event.Uint32()
		height := event.Uint32()

		for i, handler := range o.handlersForConfigure() {
			_ = i
			handler(serial, width, height)
		}
	case 1: // closed

		for i, handler := range o.handlersForClosed() {
			_ = i
			handler()
		}
	default:
	}
}
