// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: idle_inhibit_unstable_v1
// Source: idle-inhibit-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2015 Samsung Electronics Co., Ltd
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package idleinhibit

import (
	cross_wl_surface "github.com/bnema/wlturbo/protocol/core"
	"github.com/bnema/wlturbo/wl"
)

// IdleInhibitManagerInterface is the protocol interface name.
const IdleInhibitManagerInterface = "zwp_idle_inhibit_manager_v1"

// IdleInhibitManager is the generated binding for zwp_idle_inhibit_manager_v1 version 1.
type IdleInhibitManager struct {
	wl.BaseProxy
}

// NewIdleInhibitManager returns an unbound IdleInhibitManager.
func NewIdleInhibitManager(ctx *wl.Context) *IdleInhibitManager {
	obj := &IdleInhibitManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Destroy the inhibit manager.
func (o *IdleInhibitManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwp_idle_inhibit_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Create a new inhibitor object associated with the given surface.
func (o *IdleInhibitManager) CreateInhibitor(surface *cross_wl_surface.Surface) (*IdleInhibitor, error) {
	var arg1 wl.Object
	if surface != nil {
		arg1 = surface
	}
	child := &IdleInhibitor{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwp_idle_inhibit_manager_v1.create_inhibitor", Child: child}, wl.ArgObject(child), wl.ArgObject(arg1)); err != nil {
		return nil, err
	}
	return child, nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *IdleInhibitManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_idle_inhibit_manager_v1 and calls the registered handlers.
func (o *IdleInhibitManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// IdleInhibitorInterface is the protocol interface name.
const IdleInhibitorInterface = "zwp_idle_inhibitor_v1"

// IdleInhibitor is the generated binding for zwp_idle_inhibitor_v1 version 1.
type IdleInhibitor struct {
	wl.BaseProxy
}

// NewIdleInhibitor returns an unbound IdleInhibitor.
func NewIdleInhibitor(ctx *wl.Context) *IdleInhibitor {
	obj := &IdleInhibitor{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Remove the inhibitor effect from the associated wl_surface.
func (o *IdleInhibitor) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwp_idle_inhibitor_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *IdleInhibitor) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwp_idle_inhibitor_v1 and calls the registered handlers.
func (o *IdleInhibitor) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}
