// Code generated by wlturbo-scanner. DO NOT EDIT.
// Protocol: wlr_screencopy_unstable_v1
// Source: wlr-screencopy-unstable-v1.xml

// Upstream protocol copyright and license:
// Copyright © 2018 Simon Ser
// Copyright © 2019 Andri Yngvason
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package screencopy

import (
	"sync"

	cross_wl_buffer "github.com/bnema/wlturbo/protocol/core"
	cross_wl_output "github.com/bnema/wlturbo/protocol/core"
	"github.com/bnema/wlturbo/wl"
)

// ERROR_ALREADY_USED is the error already_used value.
const ERROR_ALREADY_USED = 0

// ERROR_INVALID_BUFFER is the error invalid_buffer value.
const ERROR_INVALID_BUFFER = 1

// FLAGS_Y_INVERT is the flags y_invert value.
const FLAGS_Y_INVERT = 1

// ScreencopyManagerInterface is the protocol interface name.
const ScreencopyManagerInterface = "zwlr_screencopy_manager_v1"

// ScreencopyManager is the generated binding for zwlr_screencopy_manager_v1 version 3.
type ScreencopyManager struct {
	wl.BaseProxy
}

// NewScreencopyManager returns an unbound ScreencopyManager.
func NewScreencopyManager(ctx *wl.Context) *ScreencopyManager {
	obj := &ScreencopyManager{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Capture the next frame of an entire output.
func (o *ScreencopyManager) CaptureOutput(overlayCursor int32, output *cross_wl_output.Output) (*ScreencopyFrame, error) {
	var arg2 wl.Object
	if output != nil {
		arg2 = output
	}
	child := &ScreencopyFrame{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_screencopy_manager_v1.capture_output", Child: child}, wl.ArgObject(child), wl.ArgInt(overlayCursor), wl.ArgObject(arg2)); err != nil {
		return nil, err
	}
	return child, nil
}

// Capture the next frame of an output's region. The region is given in output logical coordinates, see xdg_output.logical_size. The region will be clipped to the output's extents.
func (o *ScreencopyManager) CaptureOutputRegion(overlayCursor int32, output *cross_wl_output.Output, x int32, y int32, width int32, height int32) (*ScreencopyFrame, error) {
	var arg2 wl.Object
	if output != nil {
		arg2 = output
	}
	child := &ScreencopyFrame{}
	child.SetContext(o.Context())
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_screencopy_manager_v1.capture_output_region", Child: child}, wl.ArgObject(child), wl.ArgInt(overlayCursor), wl.ArgObject(arg2), wl.ArgInt(x), wl.ArgInt(y), wl.ArgInt(width), wl.ArgInt(height)); err != nil {
		return nil, err
	}
	return child, nil
}

// All objects created by the manager will still remain valid, until their appropriate destroy request has been called.
func (o *ScreencopyManager) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "zwlr_screencopy_manager_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// EventSignature returns the declared event argument types in wire order.
func (o *ScreencopyManager) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_screencopy_manager_v1 and calls the registered handlers.
func (o *ScreencopyManager) Dispatch(event *wl.Event) {
	switch event.Opcode {
	default:
	}
}

// ScreencopyFrameInterface is the protocol interface name.
const ScreencopyFrameInterface = "zwlr_screencopy_frame_v1"

// ScreencopyFrame is the generated binding for zwlr_screencopy_frame_v1 version 3.
type ScreencopyFrame struct {
	wl.BaseProxy
	// handlersMu guards the handler slices: a client may register or replace
	// handlers while another goroutine dispatches events.
	handlersMu    sync.Mutex
	onBuffer      []func(format uint32, width uint32, height uint32, stride uint32)
	onFlags       []func(flags uint32)
	onReady       []func(tvSecHi uint32, tvSecLo uint32, tvNsec uint32)
	onFailed      []func()
	onDamage      []func(x uint32, y uint32, width uint32, height uint32)
	onLinuxDmabuf []func(format uint32, width uint32, height uint32)
	onBufferDone  []func()
}

// NewScreencopyFrame returns an unbound ScreencopyFrame.
func NewScreencopyFrame(ctx *wl.Context) *ScreencopyFrame {
	obj := &ScreencopyFrame{}
	obj.SetContext(ctx)
	ctx.Register(obj)
	return obj
}

// Copy the frame to the supplied buffer. The buffer must have the correct size, see zwlr_screencopy_frame_v1.buffer and zwlr_screencopy_frame_v1.linux_dmabuf. The buffer needs to have a supported format. If the frame is successfully copied, "flags" and "ready" events are sent. Otherwise, a "failed" event is sent.
func (o *ScreencopyFrame) Copy(buffer *cross_wl_buffer.Buffer) error {
	var arg0 wl.Object
	if buffer != nil {
		arg0 = buffer
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 0, Name: "zwlr_screencopy_frame_v1.copy"}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// Destroys the frame. This request can be sent at any time by the client.
func (o *ScreencopyFrame) Destroy() error {
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 1, Name: "zwlr_screencopy_frame_v1.destroy", Destructor: true}); err != nil {
		return err
	}
	return nil
}

// Same as copy, except it waits until there is damage to copy.
func (o *ScreencopyFrame) CopyWithDamage(buffer *cross_wl_buffer.Buffer) error {
	var arg0 wl.Object
	if buffer != nil {
		arg0 = buffer
	}
	if err := o.Context().RequestArgs(wl.Request{Proxy: o, Opcode: 2, Name: "zwlr_screencopy_frame_v1.copy_with_damage", Since: 2}, wl.ArgObject(arg0)); err != nil {
		return err
	}
	return nil
}

// OnBuffer registers a handler for the buffer event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ScreencopyFrame) OnBuffer(handler func(format uint32, width uint32, height uint32, stride uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onBuffer = append(o.onBuffer, handler)
}

// handlersForBuffer returns the handlers registered for buffer, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ScreencopyFrame) handlersForBuffer() []func(format uint32, width uint32, height uint32, stride uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onBuffer
}

// OnFlags registers a handler for the flags event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ScreencopyFrame) OnFlags(handler func(flags uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onFlags = append(o.onFlags, handler)
}

// handlersForFlags returns the handlers registered for flags, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ScreencopyFrame) handlersForFlags() []func(flags uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onFlags
}

// OnReady registers a handler for the ready event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ScreencopyFrame) OnReady(handler func(tvSecHi uint32, tvSecLo uint32, tvNsec uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onReady = append(o.onReady, handler)
}

// handlersForReady returns the handlers registered for ready, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ScreencopyFrame) handlersForReady() []func(tvSecHi uint32, tvSecLo uint32, tvNsec uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onReady
}

// OnFailed registers a handler for the failed event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ScreencopyFrame) OnFailed(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onFailed = append(o.onFailed, handler)
}

// handlersForFailed returns the handlers registered for failed, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ScreencopyFrame) handlersForFailed() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onFailed
}

// OnDamage registers a handler for the damage event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ScreencopyFrame) OnDamage(handler func(x uint32, y uint32, width uint32, height uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onDamage = append(o.onDamage, handler)
}

// handlersForDamage returns the handlers registered for damage, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ScreencopyFrame) handlersForDamage() []func(x uint32, y uint32, width uint32, height uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onDamage
}

// OnLinuxDmabuf registers a handler for the linux_dmabuf event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ScreencopyFrame) OnLinuxDmabuf(handler func(format uint32, width uint32, height uint32)) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onLinuxDmabuf = append(o.onLinuxDmabuf, handler)
}

// handlersForLinuxDmabuf returns the handlers registered for linux_dmabuf, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ScreencopyFrame) handlersForLinuxDmabuf() []func(format uint32, width uint32, height uint32) {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onLinuxDmabuf
}

// OnBufferDone registers a handler for the buffer_done event.
//
// Handlers are appended, so a second call adds another handler rather than
// replacing the first. Registration is safe while another goroutine dispatches.
func (o *ScreencopyFrame) OnBufferDone(handler func()) {
	if handler == nil {
		return
	}
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	o.onBufferDone = append(o.onBufferDone, handler)
}

// handlersForBufferDone returns the handlers registered for buffer_done, taken
// under the lock so a handler may register another handler while events are
// being dispatched.
func (o *ScreencopyFrame) handlersForBufferDone() []func() {
	o.handlersMu.Lock()
	defer o.handlersMu.Unlock()
	return o.onBufferDone
}

// EventSignature returns the declared event argument types in wire order.
func (o *ScreencopyFrame) EventSignature(opcode uint16) (string, bool) {
	switch opcode {
	case 0:
		return "uint,uint,uint,uint,", true
	case 1:
		return "uint,", true
	case 2:
		return "uint,uint,uint,", true
	case 3:
		return "", true
	case 4:
		return "uint,uint,uint,uint,", true
	case 5:
		return "uint,uint,uint,", true
	case 6:
		return "", true
	default:
		return "", false
	}
}

// Dispatch decodes one event on zwlr_screencopy_frame_v1 and calls the registered handlers.
func (o *ScreencopyFrame) Dispatch(event *wl.Event) {
	switch event.Opcode {
	case 0: // buffer
		format := event.Uint32()
		width := event.Uint32()
		height := event.Uint32()
		stride := event.Uint32()

		for i, handler := range o.handlersForBuffer() {
			_ = i
			handler(format, width, height, stride)
		}
	case 1: // flags
		flags := event.Uint32()

		for i, handler := range o.handlersForFlags() {
			_ = i
			handler(flags)
		}
	case 2: // ready
		tvSecHi := event.Uint32()
		tvSecLo := event.Uint32()
		tvNsec := event.Uint32()

		for i, handler := range o.handlersForReady() {
			_ = i
			handler(tvSecHi, tvSecLo, tvNsec)
		}
	case 3: // failed

		for i, handler := range o.handlersForFailed() {
			_ = i
			handler()
		}
	case 4: // damage
		x := event.Uint32()
		y := event.Uint32()
		width := event.Uint32()
		height := event.Uint32()

		for i, handler := range o.handlersForDamage() {
			_ = i
			handler(x, y, width, height)
		}
	case 5: // linux_dmabuf
		format := event.Uint32()
		width := event.Uint32()
		height := event.Uint32()

		for i, handler := range o.handlersForLinuxDmabuf() {
			_ = i
			handler(format, width, height)
		}
	case 6: // buffer_done

		for i, handler := range o.handlersForBufferDone() {
			_ = i
			handler()
		}
	default:
	}
}
